name: darttonconnect_plus
description: Dart SDK for TON Connect. Use it to connect your app to TON wallets via TonConnect protocol.
version: 1.0.2
homepage: https://github.com/aap17/dart_ton_plus

environment:
  sdk: '>=2.18.4 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.2
  hex: ^0.2.0
  http: ^1.0.0
  logger: ^2.5.0
  universal_html: ^2.2.1
  shared_preferences: ^2.1.2
  tonutils: ^0.5.7
  pinenacl: ^0.6.0
  flutter_ton_buttons: ^1.0.0
  url_launcher: ^6.3.1

